require:
  - rubocop-rails
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
Metrics/MethodLength:
  Max: 1000
Metrics/AbcSize:
  Max: 1000
Metrics/BlockLength:
  Max: 150
Layout/LineLength:
  Max: 200
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
