require:
  - rubocop-rails
Metrics/MethodLength:
  Max: 1000
Metrics/AbcSize:
  Max: 1000
Metrics/BlockLength:
  Max: 150
Layout/LineLength:
  Max: 200
AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
