
### Método: GET
### Rota: /api/v1/users
### Parâmetros: Nenhum
### Resposta: Um JSON contendo todos os usuários cadastrados no sistema.
###           Cada usuário é representado por um objeto com propriedades como nome, idade, genero, latitude, longitude.
GET http://localhost:3000/api/v1/users

### Método: POST
### Rota para cadastrar um novo usuário.
### Corpo da requisição: Um objeto JSON contendo os dados do novo usuário.
### Ex: { "name": "John", "age": 30, "gender": "Masculino", "latitude": "-19.92337069418504", "longitude": "-43.942577690286285" }
POST http://localhost:3000/api/v1/users
content-type: application/json

{   
    "name": "Claudiney Veloso",
    "age": 55,
    "gender": "Masculino",
    "latitude": "-19.92337069418504",
    "longitude": "-43.942577690286285"
}

###
GET http://localhost:3000/api/v1/users/99

### Método: PUT
### Rota para atualizar a localização de um usuário
### Corpo da requisição: Um objeto JSON contendo os dados do novo usuário.
### Ex: { "name": "John", "age": 30, "gender": "Masculino", "latitude": "-19.92337069418504", "longitude": "-43.942577690286285" }



PUT http://localhost:3000/api/v1/users/99
content-type: application/json
{   
  "latitude": "-19.92337069418504",
  "longitude": "-43.942577690286285"
}

###

DELETE  http://localhost:3000/api/v1/users/7

### Método: PUT
### Rota para atualizar a localização de um usuário
### Corpo da requisição: Um objeto JSON contendo os dados para atualizar a localização.
### Ex: { "name": "John", "age": 30, "gender": "Masculino", "latitude": "-19.92337069418504", "longitude": "-43.942577690286285" }

PUT  http://localhost:3000/api/v1/users/999/current_location
# "latitude": "-78.67250359171328",
# "longitude": "126.35020104942726",
{
  "latitude": "-19.92337069418504",
  "longitude": "-43.942577690286285"
}


###
GET http://localhost:3000/api/v1/items

###
POST http://localhost:3000/api/v1/items
content-type: application/json

{   
    "description": "testew",
    "score": 4
}



### Método: POST
### Rota para atualizar um usuário infectado.
### Corpo da requisição: Um objeto JSON contendo os dados do novo usuário.
### Ex: { "name": "John", "age": 30, "gender": "Masculino", "latitude": "-19.92337069418504", "longitude": "-43.942577690286285" }


POST http://localhost:3000/api/v1/infecteds
content-type: application/json
{
  "user_id_reported": 32,
  "user_id_notified": 6
}

###

GET http://localhost:3000/api/v1/users/1/inventories

###

POST http://localhost:3000/api/v1/inventories
content-type: application/json
{
  "user_id":23, 
  "items":[
    {"id":1, "description":"Água", "score":2}
    {"id":2, "description": "Comida", "score":3}, 
  ]
}

# GET
GET http://localhost:3000/api/v1/users/1/inventories/1/inventory_items


POST http://localhost:3000/api/v1/users/1/inventories/1/inventory_items
content-type: application/json


{   
    "inventory_id": "1",
    "item_id": 2,
    "quantity": 8
}

DELETE http://localhost:3000/api/v1/users/1/inventories/1/inventory_items/1






