---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    post:
      summary: Create a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                gender:
                  type: string
                latitude:
                  type: string
                longitude:
                  type: string
              required:
              - name
              - age
              - gender
              - latitude
              - longitude
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user found
        '404':
          description: user not found
  "/api/v1/infected":
    get:
      summary: Returns the percentage of infected users
      tags:
      - Infected
      responses:
        '200':
          description: Returns the percentage of infected users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      percentage:
                        type: string
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            age:
                              type: integer
                            gender:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            infected:
                              type: boolean
                            contamination_notification:
                              type: integer
                          required:
                          - name
                          - age
                          - gender
                          - latitude
                          - longitude
                          - infected
                          - contamination_notification
                    required:
                    - percentage
                    - users
  "/api/v1/uninfected":
    get:
      summary: Returns the percentage of uninfected users
      tags:
      - Uninfected
      responses:
        '200':
          description: Returns the percentage of uninfected users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      percentage:
                        type: string
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            age:
                              type: integer
                            gender:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            infected:
                              type: boolean
                            contamination_notification:
                              type: integer
                          required:
                          - name
                          - age
                          - gender
                          - latitude
                          - longitude
                          - infected
                          - contamination_notification
                    required:
                    - percentage
                    - users
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
