---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/infecteds":
    post:
      summary: Creates a new infected user record
      tags:
      - Infecteds
      parameters: []
      responses:
        '200':
          description: Infected user successfully registered
        '422':
          description: Validation error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id_reported:
                  type: integer
                user_id_notified:
                  type: integer
              required:
              - user_id_reported
              - user_id_notified
  "/api/v1/non_existent_route":
    get:
      summary: Returns 404 when the route does not exist
      tags:
      - Non-existent Route
      responses:
        '404':
          description: Route not found
  "/api/v1/items":
    post:
      summary: Create a new inventory item
      tags:
      - Items
      parameters: []
      responses:
        '201':
          description: Inventory item registered successfully
        '422':
          description: Validation error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                score:
                  type: integer
              required:
              - description
              - score
  "/api/v1/users":
    post:
      summary: Create a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                gender:
                  type: string
                latitude:
                  type: string
                longitude:
                  type: string
              required:
              - name
              - age
              - gender
              - latitude
              - longitude
    get:
      summary: Retrieves a user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: user found
        '404':
          description: user not found
  "/api/v1/infected":
    get:
      summary: Returns the percentage of infected users
      tags:
      - Infected
      responses:
        '200':
          description: Returns the percentage of infected users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      percentage:
                        type: string
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            age:
                              type: integer
                            gender:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            infected:
                              type: boolean
                            contamination_notification:
                              type: integer
  "/api/v1/uninfected":
    get:
      summary: Returns the percentage of uninfected users
      tags:
      - Uninfected
      responses:
        '200':
          description: Returns the percentage of uninfected users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      percentage:
                        type: string
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            age:
                              type: integer
                            gender:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            infected:
                              type: boolean
                            contamination_notification:
                              type: integer
  "/api/v1/lost_score":
    get:
      summary: Returns the lost score of infected users
      tags:
      - Lost Score
      responses:
        '200':
          description: Returns the lost score of infected users
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      users:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            age:
                              type: integer
                            gender:
                              type: string
                            latitude:
                              type: string
                            longitude:
                              type: string
                            infected:
                              type: boolean
                            contamination_notification:
                              type: integer
                            score:
                              type: integer
  "/api/v1/users/{id}/current_location":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: latitude
      in: query
      description: Latitude of new location
      schema:
        type: string
    - name: longitude
      in: query
      description: Longitude of new location
      schema:
        type: string
    put:
      summary: Updates the users current location
      tags:
      - Users
      responses:
        '200':
          description: Location updated successfully
        '404':
          description: User ID not found
        '422':
          description: Validation error
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
